version: "3"

services:
  namenode:
    build:
      context: ./namenode
      args:
        HADOOP_ARCHITECTURE: ${HADOOP_ARCHITECTURE}
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - spark-hadoop-network

  datanode:
    build:
      context: ./datanode
      args:
        HADOOP_ARCHITECTURE: ${HADOOP_ARCHITECTURE}
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - spark-hadoop-network
  
  resourcemanager:
    build:
      context: ./resourcemanager
      args:
        HADOOP_ARCHITECTURE: ${HADOOP_ARCHITECTURE}
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    networks:
      - spark-hadoop-network

  nodemanager:
    build:
      context: ./nodemanager
      args:
        HADOOP_ARCHITECTURE: ${HADOOP_ARCHITECTURE}
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      - spark-hadoop-network
  
  historyserver:
    build:
      context: ./historyserver
      args:
        HADOOP_ARCHITECTURE: ${HADOOP_ARCHITECTURE}
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - spark-hadoop-network

  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-master
    restart: always
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ../scripts/spark/load_data_to_hdfs.py:/scripts/load_data_to_hdfs.py
      - ../scripts/spark/read_partial_df.py:/scripts/read_partial_df.py
      - ../scripts/spark/utils/html_utils.py:/scripts/utils/html_utils.py
      - ../scripts/spark/config/config.json:/scripts/config/config.json
      - ../scripts/spark/config/schema.json:/scripts/config/schema.json
      - ../data/output.csv:/data/output.csv
      - data_volume:/mnt/data
    environment:
      - SPARK_MODE=master
    depends_on:
      - namenode
      - datanode
    networks:
      - spark-hadoop-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-worker
    restart: always
    volumes:
      - ../scripts/spark/load_data_to_hdfs.py:/scripts/load_data_to_hdfs.py
      - ../scripts/spark/read_partial_df.py:/scripts/read_partial_df.py
      - ../scripts/spark/utils/html_utils.py:/scripts/utils/html_utils.py
      - ../data/output.csv:/data/output.csv
      - data_volume:/mnt/data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-hadoop-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/materialize.min.css:/usr/share/nginx/css/materialize.min.css
      - ./nginx/default-styles.css:/usr/share/nginx/css/default-styles.css
      - data_volume:/usr/share/nginx/html/data

    depends_on:
      - namenode
      - spark-master
    networks:
      - spark-hadoop-network
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  data_volume:

networks:
  spark-hadoop-network:
    driver: bridge